name: 'Close stale issues and PR'
on:
  schedule:
    - cron: '30 1 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v4
        with:
          stale-pr-message: 'This PR is stale because it has been open 7 days with no activity. Remove stale label or comment or please update the pull request.'
          days-before-pr-stale: 1
          days-before-issue-stale: -1
          days-before-pr-close: -1
